export const configSections = [
  {
    key: "website",
    title: "站点配置",
    description: "维护后台展示名称、域名和基础运营信息。",
    fields: [
      { key: "siteName", label: "站点名称", type: "input", placeholder: "请输入站点名称" },
      { key: "siteUrl", label: "站点地址", type: "input", placeholder: "https://example.com" },
      { key: "adminEmail", label: "管理员邮箱", type: "input", placeholder: "请输入管理员邮箱" },
      { key: "siteNotice", label: "站点公告", type: "textarea", placeholder: "请输入站点公告" },
    ],
  },
  {
    key: "security",
    title: "安全配置",
    description: "统一管理登录安全和风控阈值。",
    fields: [
      { key: "jwtExpireHours", label: "登录有效期(小时)", type: "number", min: 1, max: 720 },
      { key: "loginFailLimit", label: "登录失败上限", type: "number", min: 1, max: 20 },
      { key: "ipWhitelist", label: "后台 IP 白名单", type: "textarea", placeholder: "多个 IP 用换行分隔" },
      { key: "enableOperationLog", label: "记录操作日志", type: "switch" },
    ],
  },
  {
    key: "login",
    title: "登录配置",
    description: "统一管理登录、注册和验证码开关。",
    fields: [
      { key: "allowRegister", label: "允许注册", type: "switch" },
      { key: "enableSmsLogin", label: "开启短信登录", type: "switch" },
      { key: "enableEmailLogin", label: "开启邮箱登录", type: "switch" },
      { key: "loginTips", label: "登录页提示", type: "textarea", placeholder: "请输入登录页提示文案" },
    ],
  },
  {
    key: "storage",
    title: "存储配置",
    description: "维护素材上传和资源访问设置。",
    fields: [
      { key: "storageType", label: "素材保存方式", type: "select", options: ["local", "minio", "oss"] },
      { key: "bucketName", label: "素材空间名称", type: "input", placeholder: "请输入素材空间名称" },
      { key: "publicHost", label: "访问域名", type: "input", placeholder: "请输入资源访问域名" },
      { key: "uploadLimitMb", label: "上传大小上限(MB)", type: "number", min: 1, max: 500 },
    ],
  },
  {
    key: "live",
    title: "直播配置",
    description: "维护开播、观看和审核相关的直播参数。",
    fields: [
      { key: "pushDomain", label: "开播接入地址", type: "input", placeholder: "请输入开播接入地址" },
      { key: "playDomain", label: "观看播放地址", type: "input", placeholder: "请输入观看播放地址" },
      { key: "enableLiveAudit", label: "开启直播审核", type: "switch" },
      { key: "auditHint", label: "审核提示", type: "textarea", placeholder: "请输入主播侧提示文案" },
    ],
  },
]

export const defaultConfigState = {
  siteName: "PulseLive",
  siteUrl: "https://www.pulselive.example",
  adminEmail: "admin@pulselive.example",
  siteNotice: "欢迎来到 PulseLive，精彩直播正在进行。",
  jwtExpireHours: 24,
  loginFailLimit: 5,
  ipWhitelist: "",
  enableOperationLog: true,
  allowRegister: true,
  enableSmsLogin: false,
  enableEmailLogin: true,
  loginTips: "请使用已绑定的手机号或邮箱完成登录。",
  storageType: "local",
  bucketName: "ant-live-local",
  publicHost: "https://assets.pulselive.example",
  uploadLimitMb: 20,
  pushDomain: "https://live.pulselive.example/start",
  playDomain: "https://live.pulselive.example/watch",
  enableLiveAudit: false,
  auditHint: "开播前请确认画面、声音和直播内容符合平台规范。",
}
