#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Apr 25 10:44:26 CST 2026
maven-metadata-alimaven.xml.error=Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/to alimaven (https\://maven.aliyun.com/repository/public)\: Permission denied\: getsockopt
maven-metadata-alimaven.xml/@default-alimaven-https\://maven.aliyun.com/repository/public/.lastUpdated=1777085066202
maven-metadata-central.xml.lastUpdated=1776666687763
